Automattic/dops-components

- client/components/chart/index.jsx
This PR removes incorrect usage of `translate` with numbers and adds a `toLocaleString` call instead.
> I18n: fixed translate usage with variables.

- client/components/chart/index.jsx
The app was failing.  
I'd like to propose that in the future we can pass this string via a prop, so that it can be translated by the app.  I can make this happen later, but for now we need the app to work.
> Chart: Remove non-existent i18n function

- client/components/notice/index.jsx
Also use polyfill for the translate() method.  This thing is now usable
```
<SimpleNotice text='yo! notice!' />
```
> Notices: fix deprecated use of joinClasses, use classNames instead.

- client/lib/analytics/index.js
So that we can send events prefixed with `jetpack_`
> Analytics: whitelist the `jetpack_` prefix for tracks events.

- client/components/foldable-card/style.scss
This aims to have consistent spacing at the beginning or at the end of a card. Since the card already applies a padding, when a `p` tag is at the bottom of a card it introduces additional spacing that makes things look uneven.
> Foldable Card: make space consistent when p tags are at the beginning or at the end

- client/components/foldable-card/index.jsx
- client/components/foldable-card/style.scss
Sometimes, like in Jetpack when you already have a clickable item (toggle) in the header, you still want part of the header to be clickable and expand, but not the whole thing, as it would clash with the toggle.  This allows just the header text to be clickable.
Also adds the existing `clickableHeader` to the listed propTypes, as it was missing from there before.
To test: 
Get this branch linked to any Jetpack branch, and add `clickableHeaderText={ true }` to any `FoldableCard`
> Foldable Card: New prop clickableHeaderText 

- client/components/chart/style.scss
> Chart Tooltip: fixes misalignment in arrow tip

- client/components/notice/index.jsx
- client/components/notice/style.scss
Made a couple of small adjustments in regard to naming conventions of notices and icon position. 
Changed the name of `.notice` to `.dops-notice` since the general `.notice` class name is used by core, and potentially other plugins, which could make it fairly susceptible to style bleeding. 
Fixing issues in: https://github.com/Automattic/jetpack/pull/3974
Related changes: https://github.com/Automattic/akismet-react/pull/20
Before:
After:
> Enhancement: global notice adjustments

- client/components/notice/style.scss
- client/scss/extends.scss
- The warning and error icons were the same from before this PR.
- If this is added, maybe we don't need to add https://github.com/Automattic/jetpack/pull/4040. We might add the portion that makes the function `wpcom_static_url` visible throughout the Jetpack plugin, but it might not be necessary to add the line that enqueues the icons in the Jetpack React UI.
> Notices: change the icons used from Noticons to Dashicons.

- client/components/button/style.scss
- client/components/form/form-toggle/style.scss
- client/components/section-nav/style.scss
Helps resolve https://github.com/Automattic/jetpack/issues/3900
Fixes:
* Button
* Form-toggle (actually adds one back in)
* SectionNav
Note: leaves normal link focus styles in tact for now.
> Removes default WordPress admin focus styles on a few elements.

- client/components/section-nav/style.scss
- client/components/select-dropdown/index.jsx
- client/components/select-dropdown/style.scss
Before, section nav was completely broken when you got to smaller viewports.  This fixes both instances for viewports `above 480px` and `below 480px`.
This also updates the styles to use dashicons to show the arrows.  
To test: 
- Link this branch to https://github.com/Automattic/jetpack/pull/4339
- Follow the instructions in that PR.
> Fix section nav dropdowns on smaller screens

- client/components/notice/index.jsx
- client/components/notice/notice-action.jsx
- client/components/notice/style.scss
This PR seeks to update the notices to current Calypso.  
- Adds notice actions
- Adds compact styles && matching calypso styles.  
- Changes the dismiss onClick propname to `onDismissClick`
To test: 
- npm link this and test your notices.  They should look the same.  The onClick for dismiss should be expected to be broken.  Will fix that in another PR once this is merged.
> Update notices to current calypso

- client/components/section-header/index.jsx
- client/components/section-header/style.scss
Moves the badges from the right section to the left next to the title as designed.
CC @dereksmart or @jeffgolenski for review
> SectionHeader: moved cardBadge location

- client/components/form/form-toggle/index.jsx
react/addons is deprecated and throws `Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.` when it's used.
We should patch all files but since we're close to the alpha I've solved this one for now which is the one throwing a warning in JPR.
To test, fetch the branch and in command line, go to `dops-components` directory and run 
```
npm link
```
go to `jetpack` plugin directory and run
```
npm link @automattic/dops-components
```
> Require react instead of react/addons to eliminate JS warnings

- client/components/chart/style.scss
fixes https://github.com/Automattic/jetpack/issues/4487
To test: 
- npm link dops-components and hack [this conditional](https://github.com/Automattic/dops-components/blob/master/client/components/chart/index.jsx#L126) to say `true`
- See that there is an icon
> Chart:  Use Dashicon for emtpy stats icon.

- client/components/checkbox/README.md
- client/components/checkbox/index.jsx
- client/components/checkbox/style.scss
This pulls in the Checkbox styles and work done [here](https://github.com/Automattic/wp-calypso/pull/5323) in an initial commit. We can still use the old FormCheckbox component in the meantime while we switch over. (better than a big PR).
Before:
After:
> Checkbox: added full checkbox component with Calypso styles

- client/components/checkbox/style.scss
Fixes https://github.com/Automattic/jetpack/issues/4655
Before:
After:
CC @oskosk for review
> Checkbox: fixed to use dashicons instead of noticons for now

- client/components/text-input/style.scss
Looks like we had a sneaky box shadow make its way onto our input. (Ignore the spacing on the copy button. Fixing that shortly)
Before:
After:
> TextInput: removed box shadow inherited from wp-admin styles

- client/components/clipboard-button-input/style.scss
> ClipboardButton: fixes position of button

- client/components/search/style.scss
@dereksmart Can you spot the differences?
Before:
After:
> Search: remove inherited box shadow and margin

- client/components/external-link/README.md
- client/components/external-link/index.jsx
- client/components/external-link/style.scss
Pulls in the ExternalLink component from Calypso.
To test:
go to <adding shortly>
Looks like this:
> Adds ExternalLink component

- client/components/external-link/index.jsx
Importing lodash globally, even when using destructuring the required methods, creates the window._ variable which may collapse with underscore as is the case inside a WordPress enviornment
> ExternalLink component: Import only specific lodash methods in ExternalLink component.

- client/components/foldable-card/style.scss
To Test:
* go to a setting and click the expand button
Before:
After:
> FoldableCard: removed outline in favor of changing chevron color

- client/components/form/clipboard-button/index.jsx
Fixes Automattic/jetpack#5094
After upgrading to Babel 6, mixing usages of `export default` and `require()` does not work in the same way as before.
1. On Jetpack, with this module `npm link`ed to this branch, try to expand the **Post By Email** card under the **Writing** tab.
1. Expect to see the card expand normally.
> ClipboardButton: Import Button using ES6 modules syntax in ClipboardButton instead of require()

- client/components/global-notices/style.scss
Fixes https://github.com/Automattic/jetpack/issues/5042
Fixes https://github.com/Automattic/jetpack/issues/5057
> Global Notices: fix z-index so it doesn't conflict with search icon z-index

- .gitignore
- package.json
Currently, `dops-components` is quite strict in the versions of React defined in its dependencies.
This can cause some issues for projects using React 15.x.x and dops-components as they might be bundling 2 versions of react (with webpack for instance).
This PR makes `react` and `react-dom` peer and dev dependencies with broader version support for peer dependencies.
It also explicitly upgrades `react-formsy` to `0.18.1` (even though this version matched `^0.17.0`) because it officially supports both versions of react: https://github.com/christianalfoni/formsy-react/blob/v0.18.1/package.json#L45
> Accept new versions of React as peer dependencies

- client/components/notice/style.scss
cc @MichaelArestad @jeffgolenski 
This fixes this issue https://github.com/Automattic/jetpack/issues/5325 but would like to know if this won't break anything else.
> Notices: removes double icon displayed

- client/components/popover/style.scss
This is so there's a fallback case if side isn't defined.
This helps the building process when it's used in Jetpack with node-sass 3.7.2 and node 6.2.1
Companion to https://github.com/Automattic/jetpack/pull/4295
cc @zinigor
> Popover: add else branch in tip-arrow mixing

- package.json
As of #64, this package needs to be installed in every repo that transpiles `dops-components` or it fails when that repo (such as Delphin) tries to build anything from `dops-components`:
```bash
ERROR in ./~/@automattic/dops-components/client/components/gridicon/index.jsx
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/drewblaisdell/Desktop/a8c/delphin/node_modules/@automattic/dops-components/.babelrc" at
0, attempted to resolve relative to "/Users/drewblaisdell/Desktop/a8c/delphin/node_modules/@automattic/dops-components"
at /Users/drewblaisdell/Desktop/a8c/delphin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
at Array.map (native)
at Function.normalisePlugins …
```
> Move `babel-plugin-add-module-exports` to `dependencies`

- client/components/popover/index.jsx
- client/lib/store-transactions/index.js
Introduced in response to https://github.com/Automattic/jetpack/issues/5724
Regardless of whether it fixes that issue or not, this PR should be merged anyway since IE doesn't support Object.assign and will throw JS errors. By using lodash's `assign` we can avoid these issues.
> Use lodash's assign() to avoid errors in IE which doesn't support Object.assign

- client/components/section-header/index.jsx
- client/components/section-header/style.scss
Fixes https://github.com/Automattic/jetpack/issues/5565
To test:
* switch to `fix/5565` branch on Jetpack
* go to dashboard
* change a dashboard title to be really long or switch to Russian
* resize the window a bunch
> Fixes section-header component when strings get too long

- LICENSE.md
- package.json
We noticed that license information is missing while working on final changes before we open source code behind https://get.blog :)
This is what script using [nlf package](https://www.npmjs.com/package/nlf) generates at the moment:
This PR adds license we use across Automattic and adds link to the repository in `package.json`. This should be enough to make `dops-components` look similar to `deep-freeze`.
> Add license information

- client/components/modal/index.jsx
- client/components/modal/style.scss
This solves an issue noticed in Jetpack admin: when the body was opened, the page jumped towards left. This is due to the `position:fixed` that was applied.
This PR offers a solution to this and preserves the desired behavior in iOS devices of not scrolling the body behind the modal when it's open.
To test, use this Jetpack branch https://github.com/Automattic/jetpack/pull/6159 and
- go to your local clone of `dops-component` repo, switch to this branch `fix/body-jump-modal-open`
- do `npm link`
- go to `jetpack`, switch to this branch `add/general-settings`
- do `npm link @automattic/dops-component`
- do `yarn build`
> Fix issue where body jumps when modal is open

- client/components/form/form-toggle/index.jsx
- client/components/select-dropdown/index.jsx
- client/components/select-dropdown/style.scss
For this component this PR seeks to resolve an issue where the `disabled` property works for keys but not for click events.
Before this PR, if you pass `disabled` as property, the toggle is visually "disabled" but in reality you can still click the element.
In this component the disabled state didn't existed. It has now been implemented and it looks like a disabled TextInput.
> FormToggle, SelectDropdown: if it's disabled, disable click events.

- client/components/form/form-toggle/index.jsx
- client/components/form/form-toggle/style.scss
- client/components/form/form-toggle/test/index.jsx
The only difference from Calypso we're doing is extending `FormToggle` off of `Component` rather than `PureComponent`, because `PureComponent` is only available in React versions > 15.something and I didn't want to go down that rabbit hole.  
To Test: 
- Link to https://github.com/Automattic/jetpack/pull/6425
- Make sure toggles look/work as expected
> Update form-toggle to latest Calypso

- client/components/modal/index.jsx
Fixes #85 
This PR solves a warning regarding `this.getDOMNode()` that was deprecated as of React 0.14 and replaced by `ReactDOM.findDOMNode(this)`.
See https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#new-deprecations-introduced-with-a-warning
Reported
https://github.com/Automattic/jetpack/pull/6287#issuecomment-277384301
> Modal: replace getDOMNode() call to avoid issuing a warning in JS console.

- client/components/form/form-toggle/style.scss
You can test on: https://github.com/Automattic/jetpack/pull/6516
> FormToggle: updated flex stuff so that the label now correctly indents

- client/components/foldable-card/index.jsx
This is to ensure that if there's a foldable card within a form, it will not submit on expand.  I don't think there's any situation where that would be expected behavior.
> Set foldable card arrow dropdown button to type=button

- client/components/section-header/style.scss
Before
After
Comparison with Calypso
> Settings UI: make section header text dark instead of gray to match Calypso

- client/components/search/index.jsx
- client/components/search/style.scss
- client/mixins/url-search/README.md
- client/mixins/url-search/build-url.js
- client/mixins/url-search/index.js
- client/scss/z-index.scss
This aims to fix https://github.com/Automattic/jetpack/issues/6414 by adding changes from wp-calypso. The new component should work out of the box with the same usage interface, but currently it has some styling problems. @MichaelArestad can you please take a look at this?
This is what search looks now when it's closed:
And that's what it looks like when it's open:
> Ported over changes to the search component from wp-calypso.

- client/components/banner/style.scss
- client/components/card/style.scss
- client/components/plans/plan-icon/index.jsx
- client/components/plans/plan-icon/style.scss
This PR updates plan icons, plus updates card styles in order to fix the text going over the arrow on the banner. Copying the Card styles from Calypso resulted in a bunch of styles being removed, please make sure that I haven't removed anything that needs to stay.
cc @MichaelArestad 
This fixes https://github.com/Automattic/jetpack/issues/6505
> Updated plan icons and card styles.

- client/components/info-popover/index.jsx
- client/components/search/index.jsx
- client/lib/analytics/index.js
This adds a new function for use in tracks, that will help standardize click events from Jetpack wp-admin.  I wrote it so it can take both an object or a string as a property.  
This PR also fixes a couple of components to allow click tracking to be handled on the `onClick` property events for Sarch and Popover components.
> New tracks function `recordJetpackClick`

- client/components/popover/index.jsx
It was causing a scroll to top on first click.  
Introduced in #106
Fixes: https://github.com/Automattic/jetpack/issues/6824
To Test: 
Link this branch with any branch in Jetpack.  Follow the instructions in the issue linked to reproduce/check the patch.
> Popover: remove tabIndex attribute for div

- .eslintrc
- client/components/form/input-select.jsx
- client/components/hover-icon/index.jsx
- client/components/icon.jsx
- client/components/my-sites-navigation/current-site/index.jsx
- client/components/my-sites-navigation/site-selector/index.jsx
- client/components/payment/credit-card-selector.jsx
- client/components/slider/index.jsx
- client/components/tabs/index.jsx
A quick PR-on-a-PR for updating the accessibility linting rules. This removes the jsx-a11y rules from being set in our `eslintrc`, and instead relies on the recommended ruleset from the eslint-plugin-jsx-a11y project itself. You can see [the rules they define here](https://github.com/evcohen/eslint-plugin-jsx-a11y#difference-between-recommended-and-strict-mode). (which is what the original set was based on)
I also removed the file-level disabling of rules, since I think we should be fixing those, not ignoring them.
This can be merged into #109 if you want, @gravityrail -- I didn't want to just push to your PR.
> Update accessibility linter rules to latest version

- client/components/form/form-toggle/style.scss
Fixes https://github.com/Automattic/jetpack/issues/6878 (package will need to be published and updated).
Related https://github.com/Automattic/wp-calypso/pull/13265 (same PR in Calypso / same fix).
`FormToggle` were only activating the toggle's hover state when the toggle itself was hovered. The entire label is clickable, so it makes sense to show the hover state when any part of the clickable label is hovered. This PR makes hover on the entire clickable area activate the toggle hover state.
cc: @jeherve
> Add hover to FormToggle on label hover

- client/components/clipboard-button-input/index.jsx
Upgrading to React 15, shows that this component is passing down non-standard props to the `<input>` HTML element created by `TextInput`.
1. npm link dops-components in your Jetpack dev env.
1. Build Jetpack
1. Visit the Jetpack Settings Admin Page
1. Confirm that you see no warning related to properties being passed down to `input` from `TextInput`.
> ClipboardButtonInput: Avoid forwarding unsupported props to the HTML input element
